[package]
name = "minecraft-net"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = { version = "1.0.35", features = ["zlib"], default-features = false }
openssl = "0.10.68"
rand = "0.9.0-beta.0"
crab_nbt = "0.2.4"
bytes = "1.8.0"